name: Synchronize to forked repository
on:
    push:
        branches:
            - develop

jobs:
    sync:
        name: Sync forked repo
        runs-on: ubuntu-latest

        steps:
            - name: Checkout develop
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: develop

            - name: Set Git identity
              run: |
                  git config user.name "yuna872"
                  git config user.email "yunae426@gmail.com"

            - name: Add remote-url
              run: |
                  git remote add forked-repo https://yuna872:${{ secrets.PAT_TOKEN }}@github.com/yuna872/coffee-frontend-deploy.git
                  git remote -v

            - name: Push to forked repo
              run: |
                  git push -f forked-repo develop

            - name: Clean up
              run: |
                  git remote remove forked-repo
