name: Synchronize to forked repo
on:
    push:
        branches:
            - develop

jobs:
    sync:
        name: Sync forked repo
        runs-on: ubuntu-latest

        steps:
            - name: Checkout main
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0
                  ref: develop

            - name: Add remote-url
              run: |
                  git remote add forked-repo https://yuna872:${{ secrets.GITHUB_TOKEN }}@github.com/yuna872/coffee-frontend-deploy
                  git config user.name yuna872
                  git config user.email yunae426@gmail.com

            - name: Push changes to forked-repo
              run: |
                  git push -f forked-repo main

            - name: Clean up
              run: |
                  git remote remove forked-repo
